project_id: "427504"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
preserve_hierarchy: true

files:
  - source: "src/main/resources/assets/dawn/lang/en_us.json"
    translation: "src/main/resources/assets/dawn/lang/%locale_with_underscore%.json"
    dest: "dawn.json"