name: Feature Request
description: Suggest an idea for this mod
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for the Dawn API!
  - type: textarea
    id: content
    attributes:
      label: What is your idea about?
      placeholder: A utility class, a new command, or something else?
    validations:
      required: true