name: Test

# Triggers
on:
  release:
    types:
      - published

jobs:
  get_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Output Changelog
        run: |
          echo "Changelog: ${{ github.event.release.body }}"